contact_links:
  - name: ðŸ’¬ Misskey official Discord
    url: https://discord.gg/Wp8gVStHW3
    about: Chat freely about Misskey
  - name: ðŸ’¬ CherryPick official Discord
    url: https://discord.gg/V8qghB28Aj
    about: Chat freely about CherryPick
