name: API report (cherrypick.js)

on:
  push:
    paths:
      - packages/cherrypick-js/**
      - .github/workflows/api-cherrypick-js.yml
  pull_request:
    paths:
      - packages/cherrypick-js/**
      - .github/workflows/api-cherrypick-js.yml
jobs:
  report:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm --filter cherrypick-js build

      - name: Check files
        run: ls packages/cherrypick-js/built

      - name: API report
        run: pnpm --filter cherrypick-js api-prod

      - name: Show report
        if: always()
        run: cat packages/cherrypick-js/temp/cherrypick-js.api.md
